### PR TITLE
Update copy and help text

### PR DESCRIPTION
**Pull request by rbrtmrtn**
This PR reflects changes made to the CityAtlas landing page as well as help text in each of the topics.

### CODE REVIEW

**Comment by phaedratinder-phila** [comment]
@rbrtmrtn I noticed one place where I didn't update the doc text to match the final draft -- under 311 it's supposed to be "caller" instead of "client"

**Comment by rbrtmrtn** [comment]
I can take a look on Monday. I did change calls => requests since not all service requests are phoned in. IMO clients vs. callers follows the same logic, but that wasn't intentional.

**Comment by phaedratinder-phila** [comment]
Calls was actually updated to requests in the final draft for the same reason, but then you caught it on your own.  I see the logic, caller just sounds a little friendlier.  Super minor either way.

**Comment by phaedratinder-phila** [comment]
Calls was actually updated to requests in the final draft for the same reason, but then you caught it independently. I see the logic, caller just sounds a little friendlier. Super minor either way.

**Pull request merged**
